version: "3.9"

services:
  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ../data/redis:/root/redis
    environment:
      - REDIS_PASSWORD=12345
      - REDIS_PORT=6379
      - REDIS_DATABASES=0