version: "3.9"

services:
  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ../data/redis:/root/redis
    environment:
      - REDIS_PASSWORD=12345
      - REDIS_PORT=6379
      - REDIS_DATABASES=0

  postres:
    image: postgres
    container_name: postgres-db
    environment:
      - POSTGRES_PASSWORD=12345
      - POSTGRES_USERNAME=postgres
      - POSTGRES_DATABASE=postgres
      - POSTGRES_ROOT_PASSWORD=12345
    ports:
      - "5432:5432"

  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: 12345
    ports:
      - "5050:80"

  consul:
    image: consul:1.15.4
    ports:
      - "8500:8500"
    healthcheck:
      test: [ "CMD-SHELL", "consul info" ]
      interval: 3s
      timeout: 3s
      retries: 5