name: Release

permissions:
  contents: write

on:
  push:
    tags:
      - v[0-9]+.*

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: Set SOURCE_TAG output
      - uses: taiki-e/create-gh-release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

  upload-assets:
    needs: create-release
    runs-on: ubuntu-latest
    steps:
      - name: Set TAG variable
        run: echo "TAG=$(echo "${{ github.ref }}" | sed -n 's/refs\/tags\///p')" >> $GITHUB_ENV

      - uses: actions/checkout@v4
      - name: Install musl-tools on Linux
        run: sudo apt-get update --yes && sudo apt-get install --yes musl-tools

      - name: Install tools
        run: |
          sudo apt-get update --yes
          sudo apt-get install make
          sudo apt-get install --yes libxi-dev libx11-dev libxcb1 libxrandr2 libdbus-1-3 libxtst-dev
          sudo apt-get update

      - name: Setup Go 1.21.3
        uses: actions/setup-go@v4
        with:
          go-version: '1.21.3'

      - name: Generate abigen
        env:
          CONTRACTS_VERSION: ${{ vars.CONTRACTS_VERSION }}
        run: make generate-abigen

      - name: Push docker image
        env:
          TAG: ${{ env.TAG }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          make build-image
          docker login -u=${DOCKER_USERNAME} -p=${DOCKER_PASSWORD}
          docker push igefined/nftique:${TAG}